### ISSUE TITLE
Release first version

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-zig#1]
Referencing https://github.com/sqids/sqids-spec/issues/14

Todos:
- [x] Implementation @lvignoli
- [x] Website update @4kimov

**Comment by lvignoli** [comment]
Main points to address before 0.1.0 are: 
- [x] ~the initialization of the alphabet and blocklist: right now it is processed at each call to sqids.encode~ not anymore
- [x] default blocklist
- [x] alphabet validation: length and characters
- [x] full test suite

I'll create dedicated issue to track them if it lingers for a while

**Comment by 4kimov** [comment]
Nice, I commented on encode params [here](https://github.com/sqids/sqids-zig/pull/2#pullrequestreview-1768867735).

Regarding the blocklist, feel free to hardcode it from here: https://raw.githubusercontent.com/sqids/sqids-blocklist/main/output/blocklist.json

**Comment by lvignoli** [comment]
@4kimov test suite is complete 😀

**Comment by 4kimov** [comment]
@lvignoli Nice, thanks for letting me know & the test suite!

A few questions for you:
1. Did I get [examples](https://sqids.org/zig) right? Is it safe to omit `defer` for simplicity?
2. Am I using constructor opts correctly in those examples? I noticed the readme passes those opts to `encode` (at the bottom of the doc)
3. Do you know if it's possible to setup Github Actions for this repo?

**Comment by lvignoli** [comment]
1. It is clearer to remove the allocator.free() calls from examples, docs (and Zig paradigm) seems sufficient.
2. Yes your usage is correct, I forgot to update, will fix asap!
3. That's the next step indeed, to automate linting and release. Zig is not 1.0 though, so every minor release may break the action, but that's expected.

**Comment by 4kimov** [comment]
Great, thank you for clarifying everything. I'll close this issue since the first version is done! Thank you for the work 💪

**Comment by lvignoli** [comment]
I'll tag a v0.1 bound to work with a recent Zig version, and setup actions after Christmas 🎄
Thank you for your nice feedback, it was a pleasure to contribute 😊

**Comment by 4kimov** [comment]
Thank you, same 🎄😊
